#!/bin/bash
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# update.sh

set -e

# Source directory where artifacts are generated by the genrule
genrule_out="blaze-genfiles/sim/coremark_test"
# Destination directory for the final artifacts
dest_dir="sim/test/testfiles"

# 4.2.1: Copy validated unified assembly coremark_unified.S
cp "${genrule_out}/coremark_unified.S" "${dest_dir}/"

# 4.2.2: Copy validated linker map coremark_unified.map
cp "${genrule_out}/coremark_unified.map" "${dest_dir}/"

# 4.2.3: Verify artifacts are exclusively in sim/test/testfiles/
# This verification is done in a separate step (e.g., in a test)

# 4.2.4: Verify no compiled ELF binaries are staged or committed
# This verification is done in a separate step (e.g., in a test)

echo "Artifacts synced to ${dest_dir}"
